service: sano-sample

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  timeout: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - '*'

functions:
  hello:
    handler: dist/index.handler
    events:
      - http:
          path: hello
          method: get
